version: '3.9'

services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ./src:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

    mysql:
        image: mysql:5.7.22
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports: 
            - "3306:3306"
        volumes: 
            - ./docker/mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
    php:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: php
        volumes:
            - ./src:/var/www/html
            - ./docker/php/config/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        ports: 
            - "9000:9000"
